version: '3.8'

services:
  web:
    container_name: django-web
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379

  celery:
    build: ./
    container_name: celery
    restart: always
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env.db.celery
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:

