version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=store_user
      - POSTGRES_PASSWORD=store_password
      - POSTGRES_DB=store_db
    ports:
      - 5432:5432

volumes:
  postgres_data:

